### ISSUE TITLE
Color Updates

### ISSUE THREAD

**Issue by Turao** [black-black-cat/monokai-alt#1]
Hi,

Please, do not take this as a rant in any way. I really like the extension, as it gave me the good looks of Monokai Alt + good syntax highlight for other formats like YAML.

Please be aware others might be using the extension when changing the color schemes.
I know it can be tempting to update the extension and give it a fresher look, but considering this is a _theme extension_, changes like these can be an issue to others.

Thanks for the amazing extension so far.

**Comment by black-black-cat** [comment]
Hey buddy.

Could you try to install old version 0.1.9 or 0.1.11 if you like the old colors. The installation steps are as follows.

![install old version](https://user-images.githubusercontent.com/15521864/99965825-63752080-2dd0-11eb-8a74-8695345c1132.gif)

And then we got the old colors back.

<img width="628" alt="image_8" src="https://user-images.githubusercontent.com/15521864/99966297-0fb70700-2dd1-11eb-8dbc-4799bb97efde.png">

**Comment by black-black-cat** [comment]
Hi, @Turao. I am closing this issue.

If you want to use the old color scheme in the latest version, please submit an new issue about enhancement.
